[versions]
agp = "8.6.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
playServicesLocation = "21.3.0"
playServicesMaps = "19.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.0" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }


# Camera
androidx-camera2 = { module = "androidx.camera:camera-camera2", version = "1.1.0" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version = "1.1.0" }
androidx-camera-view = { module = "androidx.camera:camera-view", version = "1.0.0-alpha31" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

